### ISSUE TITLE
dev mode to ease onboarding of novice React developers

### ISSUE THREAD

**Issue by joewrotehaikus** [LLAMA-Coop/Alpaca#2]
Mongoose requires an instance of MongoDB, which isn't terrible to set up, but not everyone wants to mess with it. I think it would be handy to have an environment variable that triggers the app to use a mock database that we set up. Doesn't have to persist anything, it's just to give enough to test components with.

This way, we can bring in novice React and CSS developers who can focus and test just what they're working on w/o worrying about a database.

**Comment by joewrotehaikus** [comment]
I'm looking into mongodb-memory-server
Seems like a good option. And it means that Mongoose will also be tested w/o needing a "real" MongoDB instance.

**Comment by joewrotehaikus** [comment]
So, tried mongodb-memory-server. It did not go well. I was expecting records to persist at least during the same run of the app, but no. Sometimes I can refresh the page and have records get used. Sometimes it's all gone. And it's logging in the terminal like crazy because it's looking for dependencies that it didn't install for itself. Or something. Doesn't make sense to me.

My attempts to prefill data into the mock database were even worse . . . nothing but errors.

Since solutions should not create more problems, mongodb-memory-server is not a solution. I'm looking into Docker on the advice of a friend.

**Comment by mart1d4** [comment]
Closing this issue as we're not using MongoDB anymore, although I think the main problem still applies to the current state of the app
