### ISSUE TITLE
#Discussion

### ISSUE THREAD

**Issue by mart1d4** [LLAMA-Coop/Alpaca#6]
I think for a better User eXperience inputs should be cleared once the user creates a new account, note, etc...

I also think the warnings should be displayed when the user unfocuses an input, and be removed once the user starts writing again (note that I'm referencing warnings, not tooltips, as they provide help as to what to write).

Maybe adding some kind of menu could be done for mobile use, although the current menu is just simple navigation so I think it's okay in the current state it is.

**Comment by joewrotehaikus** [comment]
Yeah, UX needs work. I'm not a huge fan of the use of <datalist>, and MDN raises accessibility concerns. I'm considering a collapsible/scrolling list of checkboxes instead.

I'm not 100% clear on what you mean by warning when an input is unfocused. I know we need better validation. I don't like how over eager it is right now, but it should also start warning when it's clear the user thinks they're done, but they're not.

**Comment by mart1d4** [comment]
What I mean is that, once the user unfocuses an input, you should call a function to check if the input is empty, and if it's not empty, then check if it follows the rules or not.
A word is missing from your first sentance. Are you talking about the `datalist` in the notes component?
